### ISSUE TITLE
rails3 branch: URL generation in mailers needs updating once background tasks work

### ISSUE THREAD

**Issue by dekstop** [emmapersky/one-click-orgs#103]
notify_creation.text.erb calls non-existent proposal_url method

**Comment by chrismear** [comment]
Specifically, URL generation methods won't (generally) work outside of the context of actually handling a web request.

**Comment by chrismear** [comment]
So it turns out that the URL generation helpers (url_for, proposal_url, etc.) don't get loaded in the context of a rake task. They work fine in the normal course of running the application, or from a Rails console, but not from a rake task... unless you do:

```
Rails::Application.reload_routes!
```

which has been included in the new background worker tasks here: 58eb4716191925b51c563b348f8a9968c6fbf584
